# Generated by Django 4.1.5 on 2023-02-09 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_agrege_usuario_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariomodel',
            old_name='tipoUsuaio',
            new_name='tipoUsuario',
        ),
    ]
