# Generated by Django 4.1.5 on 2023-01-27 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_alter_productosmodel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('estado', models.BooleanField(default=True, null=True)),
                ('producto', models.ManyToManyField(to='almacen.productosmodel')),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
    ]
